import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-white shadow-md">
          <nav className="container mx-auto flex justify-between items-center p-6">
            <h1 className="text-2xl font-bold text-gray-800">User Profile</h1>
            <div className="flex space-x-4">
              <a href="#" className="text-gray-800 hover:text-blue-500 transition duration-300">
                Home
              </a>
              <a href="#" className="text-gray-800 hover:text-blue-500 transition duration-300">
                About
              </a>
              <a href="#" className="text-gray-800 hover:text-blue-500 transition duration-300">
                Contact
              </a>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
